-- =============================================================================
-- GENIE AI - SUPABASE DATABASE SCHEMA
-- =============================================================================
-- Complete database setup for Genie AI mental health support system
-- 
-- This file contains all the necessary SQL scripts to set up the complete
-- database schema for the Genie AI application, including:
-- - User profiles and authentication
-- - Emotion tracking system
-- - Safety plan management
-- - Wellness exercise tracking
-- - Analytics and reporting views
--
-- Run this script in your Supabase SQL Editor to set up the complete database
-- =============================================================================

-- =============================================================================
-- SECTION 1: USER PROFILES SYSTEM
-- =============================================================================

-- Create profiles table
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  name TEXT,
  bio TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Users can view their own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Create a function to handle updated_at
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for updated_at
CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION handle_updated_at();

-- =============================================================================
-- SECTION 2: EMOTIONS TRACKING SYSTEM
-- =============================================================================

-- Drop existing tables if they exist (for clean setup)
DROP TABLE IF EXISTS public.emotion_entries CASCADE;
DROP TABLE IF EXISTS public.emotion_types CASCADE;

-- 1. EMOTION TYPES TABLE
-- Stores the predefined emotion types with their properties
CREATE TABLE public.emotion_types (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    color TEXT NOT NULL, -- Hex color code
    icon_name TEXT NOT NULL, -- Icon identifier for frontend
    sort_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert the predefined emotion types
INSERT INTO public.emotion_types (id, name, description, color, icon_name, sort_order) VALUES
('calm', 'Calm', 'Peaceful and relaxed', '#10b981', 'Flower2', 1),
('happy', 'Happy', 'Joyful and content', '#f59e0b', 'Sun', 2),
('sad', 'Sad', 'Down or melancholic', '#3b82f6', 'CloudRain', 3),
('anxious', 'Anxious', 'Worried or nervous', '#a855f7', 'Zap', 4),
('peaceful', 'Peaceful', 'Serene and tranquil', '#06b6d4', 'Waves', 5),
('tired', 'Tired', 'Low energy or exhausted', '#6b7280', 'Moon', 6);

-- 2. EMOTION ENTRIES TABLE
-- Stores individual user emotion entries
CREATE TABLE public.emotion_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    emotion_type_id TEXT REFERENCES public.emotion_types(id) ON DELETE CASCADE NOT NULL,
    intensity INTEGER NOT NULL CHECK (intensity >= 1 AND intensity <= 10),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Optional metadata for future enhancements
    location TEXT, -- For future location tracking
    weather TEXT, -- For future weather correlation
    tags TEXT[], -- For future tagging system
    
    -- Index for better query performance
    CONSTRAINT valid_intensity CHECK (intensity BETWEEN 1 AND 10)
);

-- 3. INDEXES FOR PERFORMANCE
CREATE INDEX idx_emotion_entries_user_id ON public.emotion_entries(user_id);
CREATE INDEX idx_emotion_entries_created_at ON public.emotion_entries(created_at);
CREATE INDEX idx_emotion_entries_user_date ON public.emotion_entries(user_id, created_at);
CREATE INDEX idx_emotion_entries_emotion_type ON public.emotion_entries(emotion_type_id);

-- 4. ROW LEVEL SECURITY (RLS)
-- Enable RLS on both tables
ALTER TABLE public.emotion_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emotion_entries ENABLE ROW LEVEL SECURITY;

-- Emotion types policies (readable by all authenticated users)
CREATE POLICY "Everyone can view emotion types" 
ON public.emotion_types 
FOR SELECT 
USING (auth.uid() IS NOT NULL);

-- Emotion entries policies (users can only access their own data)
CREATE POLICY "Users can view own emotion entries" 
ON public.emotion_entries 
FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own emotion entries" 
ON public.emotion_entries 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own emotion entries" 
ON public.emotion_entries 
FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own emotion entries" 
ON public.emotion_entries 
FOR DELETE 
USING (auth.uid() = user_id);

-- 5. UPDATED_AT TRIGGER FUNCTION
-- Create function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION handle_emotion_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to emotion_entries table
CREATE TRIGGER emotion_entries_updated_at
  BEFORE UPDATE ON public.emotion_entries
  FOR EACH ROW
  EXECUTE FUNCTION handle_emotion_updated_at();

-- Apply trigger to emotion_types table
CREATE TRIGGER emotion_types_updated_at
  BEFORE UPDATE ON public.emotion_types
  FOR EACH ROW
  EXECUTE FUNCTION handle_emotion_updated_at();

-- 6. HELPFUL VIEWS FOR ANALYTICS
-- View for daily emotion summaries
CREATE OR REPLACE VIEW public.daily_emotion_summary AS
SELECT 
  user_id,
  DATE(created_at) as entry_date,
  COUNT(*) as total_entries,
  ROUND(AVG(intensity), 1) as avg_intensity,
  ARRAY_AGG(DISTINCT emotion_type_id) as emotions_felt,
  MAX(created_at) as last_entry_time
FROM public.emotion_entries
GROUP BY user_id, DATE(created_at)
ORDER BY entry_date DESC;

-- View for weekly emotion trends
CREATE OR REPLACE VIEW public.weekly_emotion_trends AS
SELECT 
  user_id,
  DATE_TRUNC('week', created_at) as week_start,
  emotion_type_id,
  COUNT(*) as entry_count,
  ROUND(AVG(intensity), 1) as avg_intensity,
  MIN(intensity) as min_intensity,
  MAX(intensity) as max_intensity
FROM public.emotion_entries
GROUP BY user_id, DATE_TRUNC('week', created_at), emotion_type_id
ORDER BY week_start DESC, emotion_type_id;

-- =============================================================================
-- SECTION 3: SAFETY PLAN SYSTEM
-- =============================================================================

-- Drop existing tables if they exist (for clean setup)
DROP TABLE IF EXISTS public.safety_plan_items CASCADE;
DROP TABLE IF EXISTS public.safety_plan_contacts CASCADE;
DROP TABLE IF EXISTS public.safety_plan_sections CASCADE;
DROP TABLE IF EXISTS public.safety_plans CASCADE;

-- 1. SAFETY PLANS TABLE
-- Main safety plan for each user
CREATE TABLE public.safety_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    last_reviewed_at TIMESTAMPTZ DEFAULT NOW(),
    is_shared_with_therapist BOOLEAN DEFAULT false,
    therapist_email TEXT,
    notes TEXT
);

-- 2. SAFETY PLAN SECTIONS TABLE
-- Predefined section types for safety plans
CREATE TABLE public.safety_plan_sections (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    icon_name TEXT NOT NULL,
    color TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert the predefined safety plan sections
INSERT INTO public.safety_plan_sections (id, title, description, icon_name, color, sort_order) VALUES
('warning-signs', 'Warning Signs', 'Early indicators that I need to use my safety plan', 'AlertCircle', '#ef4444', 1),
('coping-strategies', 'Coping Strategies', 'Things I can do on my own to feel better', 'Heart', '#a855f7', 2),
('safe-places', 'Safe Places', 'Locations where I feel secure and calm', 'MapPin', '#10b981', 3),
('reasons-to-live', 'Reasons to Live', 'Things that give my life meaning and purpose', 'Shield', '#3b82f6', 4);

-- 3. SAFETY PLAN ITEMS TABLE
-- Individual items within each section of a user's safety plan
CREATE TABLE public.safety_plan_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    section_id TEXT REFERENCES public.safety_plan_sections(id) ON DELETE CASCADE NOT NULL,
    content TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Ensure user can only have items in valid sections
    CONSTRAINT valid_section_user UNIQUE(user_id, section_id, content)
);

-- 4. SAFETY PLAN CONTACTS TABLE
-- Support contacts for user's safety plan
CREATE TABLE public.safety_plan_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    relationship TEXT,
    phone TEXT NOT NULL,
    email TEXT,
    available_hours TEXT,
    is_emergency_contact BOOLEAN DEFAULT false,
    is_professional BOOLEAN DEFAULT false, -- therapist, doctor, etc.
    notes TEXT,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. INDEXES FOR PERFORMANCE
CREATE INDEX idx_safety_plans_user_id ON public.safety_plans(user_id);
CREATE INDEX idx_safety_plan_items_user_id ON public.safety_plan_items(user_id);
CREATE INDEX idx_safety_plan_items_section ON public.safety_plan_items(section_id);
CREATE INDEX idx_safety_plan_items_user_section ON public.safety_plan_items(user_id, section_id);
CREATE INDEX idx_safety_plan_contacts_user_id ON public.safety_plan_contacts(user_id);
CREATE INDEX idx_safety_plan_contacts_emergency ON public.safety_plan_contacts(user_id, is_emergency_contact);

-- 6. ROW LEVEL SECURITY (RLS)
-- Enable RLS on all tables
ALTER TABLE public.safety_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.safety_plan_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.safety_plan_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.safety_plan_contacts ENABLE ROW LEVEL SECURITY;

-- Safety plan sections policies (readable by all authenticated users)
CREATE POLICY "Everyone can view safety plan sections" 
ON public.safety_plan_sections 
FOR SELECT 
USING (auth.uid() IS NOT NULL);

-- Safety plans policies (users can only access their own data)
CREATE POLICY "Users can view own safety plan" 
ON public.safety_plans 
FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own safety plan" 
ON public.safety_plans 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own safety plan" 
ON public.safety_plans 
FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own safety plan" 
ON public.safety_plans 
FOR DELETE 
USING (auth.uid() = user_id);

-- Safety plan items policies
CREATE POLICY "Users can view own safety plan items" 
ON public.safety_plan_items 
FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own safety plan items" 
ON public.safety_plan_items 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own safety plan items" 
ON public.safety_plan_items 
FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own safety plan items" 
ON public.safety_plan_items 
FOR DELETE 
USING (auth.uid() = user_id);

-- Safety plan contacts policies
CREATE POLICY "Users can view own safety plan contacts" 
ON public.safety_plan_contacts 
FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own safety plan contacts" 
ON public.safety_plan_contacts 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own safety plan contacts" 
ON public.safety_plan_contacts 
FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own safety plan contacts" 
ON public.safety_plan_contacts 
FOR DELETE 
USING (auth.uid() = user_id);

-- 7. UPDATED_AT TRIGGER FUNCTION
-- Create function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION handle_safety_plan_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply triggers to all tables
CREATE TRIGGER safety_plans_updated_at
  BEFORE UPDATE ON public.safety_plans
  FOR EACH ROW
  EXECUTE FUNCTION handle_safety_plan_updated_at();

CREATE TRIGGER safety_plan_sections_updated_at
  BEFORE UPDATE ON public.safety_plan_sections
  FOR EACH ROW
  EXECUTE FUNCTION handle_safety_plan_updated_at();

CREATE TRIGGER safety_plan_items_updated_at
  BEFORE UPDATE ON public.safety_plan_items
  FOR EACH ROW
  EXECUTE FUNCTION handle_safety_plan_updated_at();

CREATE TRIGGER safety_plan_contacts_updated_at
  BEFORE UPDATE ON public.safety_plan_contacts
  FOR EACH ROW
  EXECUTE FUNCTION handle_safety_plan_updated_at();

-- 8. HELPFUL VIEWS FOR ANALYTICS
-- View for complete safety plan with all components
CREATE OR REPLACE VIEW public.complete_safety_plans AS
SELECT 
  sp.user_id,
  sp.id as plan_id,
  sp.created_at as plan_created_at,
  sp.updated_at as plan_updated_at,
  sp.last_reviewed_at,
  sp.is_shared_with_therapist,
  sp.therapist_email,
  sp.notes as plan_notes,
  
  -- Count of items per section
  (SELECT COUNT(*) FROM safety_plan_items WHERE user_id = sp.user_id AND section_id = 'warning-signs') as warning_signs_count,
  (SELECT COUNT(*) FROM safety_plan_items WHERE user_id = sp.user_id AND section_id = 'coping-strategies') as coping_strategies_count,
  (SELECT COUNT(*) FROM safety_plan_items WHERE user_id = sp.user_id AND section_id = 'safe-places') as safe_places_count,
  (SELECT COUNT(*) FROM safety_plan_items WHERE user_id = sp.user_id AND section_id = 'reasons-to-live') as reasons_to_live_count,
  
  -- Total counts
  (SELECT COUNT(*) FROM safety_plan_items WHERE user_id = sp.user_id) as total_items,
  (SELECT COUNT(*) FROM safety_plan_contacts WHERE user_id = sp.user_id) as total_contacts,
  (SELECT COUNT(*) FROM safety_plan_contacts WHERE user_id = sp.user_id AND is_emergency_contact = true) as emergency_contacts_count
FROM public.safety_plans sp;

-- View for safety plan completeness metrics
CREATE OR REPLACE VIEW public.safety_plan_completeness AS
SELECT 
  user_id,
  CASE 
    WHEN total_items >= 10 AND total_contacts >= 2 THEN 'Complete'
    WHEN total_items >= 5 AND total_contacts >= 1 THEN 'Partial'
    ELSE 'Incomplete'
  END as completeness_status,
  ROUND(
    (LEAST(total_items, 10) * 0.7 + LEAST(total_contacts, 5) * 0.3) * 10, 1
  ) as completeness_score,
  warning_signs_count > 0 as has_warning_signs,
  coping_strategies_count > 0 as has_coping_strategies,
  safe_places_count > 0 as has_safe_places,
  reasons_to_live_count > 0 as has_reasons_to_live,
  emergency_contacts_count > 0 as has_emergency_contacts,
  last_reviewed_at,
  EXTRACT(DAYS FROM (NOW() - last_reviewed_at)) as days_since_review
FROM public.complete_safety_plans;

-- =============================================================================
-- SECTION 4: WELLNESS EXERCISE SYSTEM
-- =============================================================================

-- Drop existing tables if they exist (for clean reinstall)
DROP TABLE IF EXISTS wellness_completions CASCADE;
DROP TABLE IF EXISTS wellness_exercises CASCADE;

-- WELLNESS EXERCISES TABLE
-- Stores the available wellness exercises/activities
CREATE TABLE wellness_exercises (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    duration_seconds INTEGER NOT NULL,
    category VARCHAR(50) NOT NULL,
    difficulty VARCHAR(20) NOT NULL CHECK (difficulty IN ('beginner', 'intermediate', 'advanced')),
    color VARCHAR(7) NOT NULL, -- Hex color code
    icon_name VARCHAR(50) NOT NULL, -- Icon identifier for frontend mapping
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX idx_wellness_exercises_category ON wellness_exercises(category);
CREATE INDEX idx_wellness_exercises_difficulty ON wellness_exercises(difficulty);
CREATE INDEX idx_wellness_exercises_active ON wellness_exercises(is_active);

-- WELLNESS COMPLETIONS TABLE
-- Tracks when users complete wellness exercises
CREATE TABLE wellness_completions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    exercise_id UUID NOT NULL REFERENCES wellness_exercises(id) ON DELETE CASCADE,
    completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    actual_duration_seconds INTEGER, -- Actual time spent (may differ from exercise duration)
    notes TEXT,
    mood_before VARCHAR(50),
    mood_after VARCHAR(50),
    rating INTEGER CHECK (rating >= 1 AND rating <= 5), -- User rating of the session
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX idx_wellness_completions_user_id ON wellness_completions(user_id);
CREATE INDEX idx_wellness_completions_exercise_id ON wellness_completions(exercise_id);
CREATE INDEX idx_wellness_completions_completed_at ON wellness_completions(completed_at);
CREATE INDEX idx_wellness_completions_user_date ON wellness_completions(user_id, completed_at);

-- ROW LEVEL SECURITY (RLS) POLICIES
-- Enable RLS on wellness_completions (users can only see their own completions)
ALTER TABLE wellness_completions ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own completions
CREATE POLICY "Users can view their own wellness completions"
    ON wellness_completions FOR SELECT
    USING (auth.uid() = user_id);

-- Policy: Users can insert their own completions
CREATE POLICY "Users can insert their own wellness completions"
    ON wellness_completions FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own completions
CREATE POLICY "Users can update their own wellness completions"
    ON wellness_completions FOR UPDATE
    USING (auth.uid() = user_id);

-- Policy: Users can delete their own completions
CREATE POLICY "Users can delete their own wellness completions"
    ON wellness_completions FOR DELETE
    USING (auth.uid() = user_id);

-- Wellness exercises are public (read-only for all authenticated users)
ALTER TABLE wellness_exercises ENABLE ROW LEVEL SECURITY;

-- Policy: All authenticated users can view wellness exercises
CREATE POLICY "Authenticated users can view wellness exercises"
    ON wellness_exercises FOR SELECT
    USING (auth.role() = 'authenticated');

-- SEED DATA - WELLNESS EXERCISES
INSERT INTO wellness_exercises (name, description, duration_seconds, category, difficulty, color, icon_name) VALUES
-- Breathing Exercises
('Box Breathing', 'A calming technique to reduce stress and anxiety', 240, 'breathing', 'beginner', '#3b82f6', 'Wind'),
('4-7-8 Breathing', 'Natural tranquilizer for the nervous system', 180, 'breathing', 'intermediate', '#8b5cf6', 'Waves'),
('Coherent Breathing', 'Balanced breathing for emotional regulation', 300, 'breathing', 'beginner', '#06b6d4', 'Wind'),

-- Meditation Exercises
('Quick Body Scan', 'Release tension and increase body awareness', 300, 'meditation', 'beginner', '#ec4899', 'Activity'),
('Loving Kindness', 'Cultivate compassion for yourself and others', 300, 'meditation', 'intermediate', '#f43f5e', 'Heart'),
('Progressive Muscle Relaxation', 'Systematic tension and relaxation of muscle groups', 600, 'meditation', 'intermediate', '#a855f7', 'Activity'),

-- Grounding Exercises
('5 Senses Grounding', 'Ground yourself in the present moment', 120, 'grounding', 'beginner', '#10b981', 'Flower2'),
('54321 Technique', 'A quick grounding technique using your senses', 180, 'grounding', 'beginner', '#059669', 'Flower2'),
('Body Awareness', 'Connect with your physical presence', 240, 'grounding', 'beginner', '#047857', 'Activity'),

-- Mindfulness Exercises
('Mindful Moment', 'A brief pause to center yourself', 60, 'mindfulness', 'beginner', '#f59e0b', 'Sun'),
('Mindful Walking', 'Walking meditation for clarity and focus', 600, 'mindfulness', 'beginner', '#d97706', 'Activity'),
('Present Moment Awareness', 'Cultivate awareness of the here and now', 480, 'mindfulness', 'intermediate', '#b45309', 'Sun'),

-- Stress Relief
('Quick Stress Relief', 'Immediate techniques for stress reduction', 120, 'stress-relief', 'beginner', '#ef4444', 'Zap'),
('Anxiety Reset', 'Calming exercises specifically for anxiety', 360, 'stress-relief', 'intermediate', '#dc2626', 'Heart'),
('Emergency Calm', 'Ultra-quick calming technique for panic', 30, 'stress-relief', 'beginner', '#b91c1c', 'Zap'),

-- Focus & Concentration
('Focus Builder', 'Improve concentration and mental clarity', 420, 'focus', 'intermediate', '#7c3aed', 'Star'),
('Single-Point Focus', 'Train sustained attention', 360, 'focus', 'advanced', '#6d28d9', 'Star'),
('Clarity Meditation', 'Clear mental fog and enhance focus', 300, 'focus', 'intermediate', '#5b21b6', 'Sun');

-- ANALYTICS VIEWS
-- View for daily completion statistics
CREATE OR REPLACE VIEW wellness_daily_stats AS
SELECT 
    user_id,
    DATE(completed_at) as completion_date,
    COUNT(*) as exercises_completed,
    SUM(COALESCE(actual_duration_seconds, duration_seconds)) as total_practice_time,
    AVG(rating) as avg_rating,
    ARRAY_AGG(DISTINCT category ORDER BY category) as categories_practiced
FROM wellness_completions wc
JOIN wellness_exercises we ON wc.exercise_id = we.id
GROUP BY user_id, DATE(completed_at);

-- View for weekly trends
CREATE OR REPLACE VIEW wellness_weekly_trends AS
SELECT 
    user_id,
    DATE_TRUNC('week', completed_at) as week_start,
    COUNT(*) as exercises_completed,
    SUM(COALESCE(actual_duration_seconds, duration_seconds)) as total_practice_time,
    COUNT(DISTINCT exercise_id) as unique_exercises,
    AVG(rating) as avg_rating
FROM wellness_completions wc
JOIN wellness_exercises we ON wc.exercise_id = we.id
GROUP BY user_id, DATE_TRUNC('week', completed_at);

-- View for exercise popularity
CREATE OR REPLACE VIEW wellness_exercise_popularity AS
SELECT 
    we.id,
    we.name,
    we.category,
    COUNT(wc.id) as completion_count,
    AVG(wc.rating) as avg_rating,
    AVG(COALESCE(wc.actual_duration_seconds, we.duration_seconds)) as avg_duration
FROM wellness_exercises we
LEFT JOIN wellness_completions wc ON we.id = wc.exercise_id
GROUP BY we.id, we.name, we.category
ORDER BY completion_count DESC;

-- =============================================================================
-- SECTION 5: UTILITY FUNCTIONS
-- =============================================================================

-- Function to get user's wellness streak
CREATE OR REPLACE FUNCTION get_wellness_streak(p_user_id UUID)
RETURNS INTEGER AS $$
DECLARE
    streak_count INTEGER := 0;
    check_date DATE := CURRENT_DATE;
    has_completion BOOLEAN;
BEGIN
    -- Check each day going backwards until we find a day without completions
    LOOP
        SELECT EXISTS(
            SELECT 1 FROM wellness_completions 
            WHERE user_id = p_user_id 
            AND DATE(completed_at) = check_date
        ) INTO has_completion;
        
        IF has_completion THEN
            streak_count := streak_count + 1;
            check_date := check_date - INTERVAL '1 day';
        ELSE
            EXIT;
        END IF;
        
        -- Safety limit to prevent infinite loops
        IF streak_count > 365 THEN
            EXIT;
        END IF;
    END LOOP;
    
    RETURN streak_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get today's completions for a user
CREATE OR REPLACE FUNCTION get_todays_wellness_completions(p_user_id UUID)
RETURNS TABLE(
    exercise_id UUID,
    exercise_name VARCHAR(100),
    category VARCHAR(50),
    completed_at TIMESTAMP WITH TIME ZONE,
    actual_duration_seconds INTEGER,
    rating INTEGER
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        wc.exercise_id,
        we.name as exercise_name,
        we.category,
        wc.completed_at,
        wc.actual_duration_seconds,
        wc.rating
    FROM wellness_completions wc
    JOIN wellness_exercises we ON wc.exercise_id = we.id
    WHERE wc.user_id = p_user_id
    AND DATE(wc.completed_at) = CURRENT_DATE
    ORDER BY wc.completed_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to complete an exercise
CREATE OR REPLACE FUNCTION complete_wellness_exercise(
    p_user_id UUID,
    p_exercise_id UUID,
    p_actual_duration_seconds INTEGER DEFAULT NULL,
    p_notes TEXT DEFAULT NULL,
    p_mood_before VARCHAR(50) DEFAULT NULL,
    p_mood_after VARCHAR(50) DEFAULT NULL,
    p_rating INTEGER DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
    completion_id UUID;
BEGIN
    INSERT INTO wellness_completions (
        user_id,
        exercise_id,
        actual_duration_seconds,
        notes,
        mood_before,
        mood_after,
        rating
    ) VALUES (
        p_user_id,
        p_exercise_id,
        p_actual_duration_seconds,
        p_notes,
        p_mood_before,
        p_mood_after,
        p_rating
    ) RETURNING id INTO completion_id;
    
    RETURN completion_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to create sample safety plan for a user
CREATE OR REPLACE FUNCTION create_sample_safety_plan(user_uuid UUID)
RETURNS VOID AS $$
BEGIN
  -- Create the safety plan
  INSERT INTO public.safety_plans (user_id) 
  VALUES (user_uuid)
  ON CONFLICT (user_id) DO NOTHING;
  
  -- Add sample items for each section
  INSERT INTO public.safety_plan_items (user_id, section_id, content, sort_order) VALUES
  (user_uuid, 'warning-signs', 'Feeling overwhelmed or hopeless', 1),
  (user_uuid, 'warning-signs', 'Isolating from friends and family', 2),
  (user_uuid, 'warning-signs', 'Changes in sleep patterns', 3),
  
  (user_uuid, 'coping-strategies', 'Take a walk in nature', 1),
  (user_uuid, 'coping-strategies', 'Practice deep breathing exercises', 2),
  (user_uuid, 'coping-strategies', 'Listen to calming music', 3),
  (user_uuid, 'coping-strategies', 'Write in my journal', 4),
  
  (user_uuid, 'safe-places', 'Local park near home', 1),
  (user_uuid, 'safe-places', 'Coffee shop on Main Street', 2),
  (user_uuid, 'safe-places', 'Public library', 3),
  
  (user_uuid, 'reasons-to-live', 'My family and friends', 1),
  (user_uuid, 'reasons-to-live', 'Future goals and dreams', 2),
  (user_uuid, 'reasons-to-live', 'Helping others', 3)
  ON CONFLICT (user_id, section_id, content) DO NOTHING;
  
  -- Add sample contacts
  INSERT INTO public.safety_plan_contacts (user_id, name, relationship, phone, available_hours, is_emergency_contact) VALUES
  (user_uuid, 'Dr. Sarah Johnson', 'Therapist', '(555) 123-4567', 'Mon-Fri 9AM-5PM', false),
  (user_uuid, 'Emma', 'Best Friend', '(555) 987-6543', 'Anytime', true)
  ON CONFLICT DO NOTHING;
END;
$$ LANGUAGE plpgsql;

-- Function to create sample wellness data
CREATE OR REPLACE FUNCTION create_sample_wellness_data(p_user_id UUID)
RETURNS VOID AS $$
DECLARE
    exercise_record RECORD;
    days_back INTEGER;
    completion_time TIMESTAMP WITH TIME ZONE;
BEGIN
    -- Create sample completions for the last 7 days
    FOR days_back IN 0..6 LOOP
        completion_time := CURRENT_DATE - INTERVAL '1 day' * days_back + INTERVAL '10 hours';
        
        -- Complete 1-3 random exercises each day
        FOR exercise_record IN (
            SELECT id FROM wellness_exercises 
            WHERE is_active = true 
            ORDER BY RANDOM() 
            LIMIT floor(random() * 3 + 1)::INTEGER
        ) LOOP
            INSERT INTO wellness_completions (
                user_id,
                exercise_id,
                completed_at,
                actual_duration_seconds,
                rating,
                mood_before,
                mood_after
            ) VALUES (
                p_user_id,
                exercise_record.id,
                completion_time + INTERVAL '1 hour' * floor(random() * 10),
                NULL, -- Use exercise default duration
                floor(random() * 5 + 1)::INTEGER, -- Random rating 1-5
                (ARRAY['stressed', 'anxious', 'tired', 'neutral', 'calm'])[floor(random() * 5 + 1)],
                (ARRAY['calm', 'peaceful', 'refreshed', 'centered', 'relaxed'])[floor(random() * 5 + 1)]
            );
        END LOOP;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- SECTION 6: MIGRATION FOR EXISTING USERS
-- =============================================================================

-- Migration: Create profiles for existing users who don't have them yet
-- Run this AFTER creating the profiles table
INSERT INTO profiles (id, email, name, bio, created_at, updated_at)
SELECT 
  au.id,
  au.email,
  COALESCE(
    au.raw_user_meta_data->>'name', 
    SPLIT_PART(au.email, '@', 1)
  ) as name,
  au.raw_user_meta_data->>'bio' as bio,
  au.created_at,
  NOW()
FROM auth.users au
LEFT JOIN profiles p ON au.id = p.id
WHERE p.id IS NULL  -- Only users without existing profiles
AND au.email IS NOT NULL;

-- =============================================================================
-- SECTION 7: SETUP COMPLETION MESSAGE
-- =============================================================================

DO $$
BEGIN
    RAISE NOTICE '=============================================================================';
    RAISE NOTICE 'GENIE AI DATABASE SETUP COMPLETED SUCCESSFULLY!';
    RAISE NOTICE '=============================================================================';
    RAISE NOTICE 'Tables created:';
    RAISE NOTICE '  - profiles (user profiles)';
    RAISE NOTICE '  - emotion_types (% emotion types)', (SELECT COUNT(*) FROM public.emotion_types);
    RAISE NOTICE '  - emotion_entries (emotion tracking)';
    RAISE NOTICE '  - safety_plans (safety plan management)';
    RAISE NOTICE '  - safety_plan_sections (% predefined sections)', (SELECT COUNT(*) FROM public.safety_plan_sections);
    RAISE NOTICE '  - safety_plan_items (safety plan content)';
    RAISE NOTICE '  - safety_plan_contacts (support contacts)';
    RAISE NOTICE '  - wellness_exercises (% wellness activities)', (SELECT COUNT(*) FROM wellness_exercises);
    RAISE NOTICE '  - wellness_completions (exercise tracking)';
    RAISE NOTICE '';
    RAISE NOTICE 'Views created:';
    RAISE NOTICE '  - daily_emotion_summary';
    RAISE NOTICE '  - weekly_emotion_trends';
    RAISE NOTICE '  - complete_safety_plans';
    RAISE NOTICE '  - safety_plan_completeness';
    RAISE NOTICE '  - wellness_daily_stats';
    RAISE NOTICE '  - wellness_weekly_trends';
    RAISE NOTICE '  - wellness_exercise_popularity';
    RAISE NOTICE '';
    RAISE NOTICE 'Functions created:';
    RAISE NOTICE '  - get_wellness_streak(user_id)';
    RAISE NOTICE '  - get_todays_wellness_completions(user_id)';
    RAISE NOTICE '  - complete_wellness_exercise(...)';
    RAISE NOTICE '  - create_sample_safety_plan(user_id)';
    RAISE NOTICE '  - create_sample_wellness_data(user_id)';
    RAISE NOTICE '';
    RAISE NOTICE 'Row Level Security (RLS) is enabled - users can only see their own data.';
    RAISE NOTICE 'All existing users have been migrated to the profiles system.';
    RAISE NOTICE '';
    RAISE NOTICE 'To create sample data for testing, run:';
    RAISE NOTICE '  SELECT create_sample_safety_plan(''your-user-id-here'');';
    RAISE NOTICE '  SELECT create_sample_wellness_data(''your-user-id-here'');';
    RAISE NOTICE '=============================================================================';
END $$;
