export interface MeditationTopic {
  id: string;
  title: string;
  description: string;
  duration?: string;
  author: string;
  voice: string;
  content: string[];
  colorTheme: {
    center: string;
    mid1: string;
    mid2: string;
    edge: string;
  };
  category: 'mindfulness' | 'sleep' | 'anxiety' | 'focus' | 'healing' | 'gratitude' | 'relationships' | 'creativity';
}

// Utility function to calculate duration based on word count
export function calculateDuration(content: string[], wordsPerMinute: number = 120): string {
  const totalWords = content.reduce((sum, line) => sum + line.split(' ').length, 0);
  const pauseBetweenLines = (content.length - 1) * 1.2; // 1.2 seconds pause between lines
  const totalSeconds = (totalWords / wordsPerMinute) * 60 + pauseBetweenLines;
  
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = Math.round(totalSeconds % 60);
  
  return `${minutes}:${seconds.toString().padStart(2, '0')}`;
}

// Enhanced meditation content with longer, more diverse topics
export const meditationContent: Omit<MeditationTopic, 'duration'>[] = [
  {
    id: "ocean-of-awareness",
    title: "Ocean of Awareness",
    description: "Dive into the vast ocean of consciousness, discovering the depth and expansiveness of your true nature through mindful awareness.",
    author: "Words by Genie",
    voice: "Voice by Genie",
    category: "mindfulness",
    colorTheme: {
      center: 'rgba(180, 220, 255, 0.95)',
      mid1: 'rgba(160, 210, 245, 0.9)',
      mid2: 'rgba(140, 200, 235, 0.8)',
      edge: 'rgba(120, 180, 220, 0.6)',
    },
    content: [
      "Welcome to this journey into the ocean of awareness",
      "Find a comfortable position where your body can rest",
      "Let your eyes gently close or soften your gaze downward",
      "Begin by taking three conscious breaths",
      "Each breath deeper and more relaxing than the last",
      "",
      "Imagine yourself standing at the edge of a vast, peaceful ocean",
      "The water is calm, reflecting the infinite sky above",
      "This ocean represents your consciousness",
      "Limitless, deep, and eternally present",
      "",
      "Notice how your breath moves like gentle waves",
      "Rising and falling in a natural rhythm",
      "Each inhale brings fresh awareness",
      "Each exhale releases what no longer serves you",
      "",
      "Now begin to wade into this ocean of consciousness",
      "Feel the warm water welcoming you",
      "With each step, you move deeper into awareness",
      "The water supports you completely",
      "You are safe, held by the ocean of your own being",
      "",
      "As you go deeper, notice how quiet it becomes",
      "The surface thoughts begin to settle",
      "Like sediment sinking to the ocean floor",
      "What remains is crystal clear awareness",
      "",
      "Float here in this spacious awareness",
      "Notice how vast your consciousness truly is",
      "It extends beyond the boundaries of your body",
      "Beyond the limits of your thoughts",
      "You are not just a drop in the ocean",
      "You are the entire ocean in a drop",
      "",
      "Feel the currents of sensation moving through you",
      "Physical sensations arise and pass like schools of fish",
      "Emotions flow through like warm and cool currents",
      "Thoughts drift by like clouds reflected on the water",
      "You observe them all from this place of deep awareness",
      "",
      "In this ocean, you discover your true depth",
      "Layer upon layer of consciousness",
      "Each one revealing more of who you truly are",
      "Beyond your roles and identities",
      "Beyond your stories and beliefs",
      "You find pure, spacious awareness",
      "",
      "Here in the depths, there is profound stillness",
      "A stillness that has always been here",
      "Waiting patiently for you to discover it",
      "This is your natural state",
      "This is your home",
      "",
      "Notice how in this depth, everything is connected",
      "Your awareness touches all things",
      "And all things arise within your awareness",
      "You are both the observer and the observed",
      "The knower and the known",
      "",
      "Rest here in this recognition",
      "You don't need to do anything",
      "Just be present in this ocean of awareness",
      "Let it wash through every cell of your being",
      "Cleansing, refreshing, renewing",
      "",
      "When thoughts arise, let them be like bubbles",
      "Rising naturally to the surface and dissolving",
      "You don't need to follow them",
      "You don't need to push them away",
      "Simply remain in the depths of awareness",
      "",
      "Feel how this ocean connects you to all life",
      "Every being swims in this same consciousness",
      "We are all waves in the same ocean",
      "Temporarily rising, expressing unique forms",
      "Yet always part of the whole",
      "",
      "Now slowly begin to return to the surface",
      "Bringing with you the peace of the depths",
      "As you rise, you carry this awareness with you",
      "It infuses your entire being",
      "",
      "Feel your body resting in its position",
      "Notice the air on your skin",
      "Hear the sounds around you",
      "All arising within this ocean of awareness",
      "",
      "Take a deep breath and know that you can return here",
      "This ocean is always within you",
      "You are never separate from this vastness",
      "It is your true nature, your essence",
      "",
      "When you're ready, gently open your eyes",
      "Look around with the eyes of the ocean",
      "See everything arising in awareness",
      "Carry this depth with you into your day",
      "Remember, you are the ocean, not just the waves"
    ]
  },
  {
    id: "mountain-of-strength",
    title: "Mountain of Strength",
    description: "Connect with your inner mountain—unshakeable, grounded, and eternally present. Find stability and strength in the midst of life's changing weather.",
    author: "Words by Genie",
    voice: "Voice by Genie",
    category: "anxiety",
    colorTheme: {
      center: 'rgba(200, 180, 160, 0.95)',
      mid1: 'rgba(180, 160, 140, 0.9)',
      mid2: 'rgba(160, 140, 120, 0.8)',
      edge: 'rgba(140, 120, 100, 0.6)',
    },
    content: [
      "Welcome to this practice of inner strength and stability",
      "Let yourself settle into a comfortable seated position",
      "Feel your connection to the earth beneath you",
      "Take a moment to arrive fully in this space",
      "",
      "Close your eyes and take three grounding breaths",
      "With each exhale, let your body grow heavier",
      "Sinking into your seat like roots into soil",
      "You are here, you are supported, you are safe",
      "",
      "Now imagine a majestic mountain before you",
      "Ancient, powerful, and utterly still",
      "This mountain has stood for millennia",
      "Witnessing countless seasons come and go",
      "Unmoved by the changing weather around it",
      "",
      "See the solid base of this mountain",
      "How it rises from the earth with natural grace",
      "Its slopes are steady and sure",
      "Its peak reaches toward the heavens",
      "Grounded below, expansive above",
      "",
      "Now recognize that you are this mountain",
      "Your seated body forms the same sacred shape",
      "Your base is rooted firmly to the ground",
      "Your spine rises like the mountain's slope",
      "Your head is the peak, touching the sky",
      "",
      "Feel the weight and solidity of your mountain body",
      "The density of rock and earth within you",
      "You are substantial, real, present",
      "Nothing can move you from your center",
      "You are grounded in your own being",
      "",
      "Like the mountain, you have weathered many storms",
      "Winds of change have blown around you",
      "Rains of sorrow have fallen upon you",
      "Snows of difficulty have covered you",
      "Yet here you stand, unchanged at your core",
      "",
      "The weather of life continues to change",
      "Sometimes the sun shines warm on your slopes",
      "Sometimes clouds gather dark around your peak",
      "Lightning may flash, thunder may roar",
      "But you, the mountain, remain steady",
      "",
      "Thoughts are like clouds passing by your peak",
      "They come and go, constantly changing",
      "You don't need to chase them or push them away",
      "Simply let them pass like weather",
      "You remain the mountain, stable and strong",
      "",
      "Emotions are like seasons on your slopes",
      "Joy might bloom like wildflowers in spring",
      "Sadness might fall like autumn leaves",
      "Anger might blaze like summer heat",
      "Fear might chill like winter frost",
      "All seasons are natural, all will pass",
      "",
      "Throughout all changes, your essence remains",
      "The core of the mountain is always still",
      "Always silent, always at peace",
      "This is your true nature",
      "Unshakeable, unchangeable, eternal",
      "",
      "Feel the strength that comes from this knowing",
      "You don't need to resist life's weather",
      "You don't need to control the seasons",
      "You simply need to remember what you are",
      "A mountain of presence and peace",
      "",
      "In your daily life, when storms arise",
      "When anxiety swirls around you like fog",
      "When fear crashes against you like waves",
      "Remember this mountain within you",
      "Return to your solid, stable core",
      "",
      "Take a moment now to feel your mountain strength",
      "Feel it in your bones, dense and strong",
      "Feel it in your breath, steady and sure",
      "Feel it in your heart, brave and open",
      "This strength is always available to you",
      "",
      "You can face whatever comes",
      "Not because you are invulnerable",
      "But because you know your true nature",
      "You are the mountain, not the weather",
      "You are the stability, not the storm",
      "",
      "Breathe in and feel your mountain dignity",
      "Breathe out and release all that is not essential",
      "With each breath, become more solid",
      "More grounded, more present",
      "More connected to your unshakeable core",
      "",
      "When you're ready, slowly open your eyes",
      "But keep the mountain within you",
      "As you move through your day",
      "Remember your strength, your stability",
      "You are a mountain of magnificent presence"
    ]
  },
  {
    id: "garden-of-the-heart",
    title: "Garden of the Heart",
    description: "Cultivate loving-kindness in the garden of your heart. Plant seeds of compassion for yourself and others, watching them bloom into boundless love.",
    author: "Words by Genie",
    voice: "Voice by Genie",
    category: "relationships",
    colorTheme: {
      center: 'rgba(255, 200, 220, 0.95)',
      mid1: 'rgba(255, 180, 200, 0.9)',
      mid2: 'rgba(240, 160, 180, 0.8)',
      edge: 'rgba(220, 140, 160, 0.6)',
    },
    content: [
      "Welcome to the garden of your heart",
      "A sacred space where love grows naturally",
      "Take a moment to settle into comfort",
      "Let your body find its natural ease",
      "Place one or both hands on your heart",
      "",
      "Feel the warmth of your own touch",
      "This simple gesture is an act of kindness",
      "Already you are tending to your garden",
      "Already you are practicing love",
      "",
      "Take three soft breaths into your heart space",
      "With each breath, imagine your heart opening",
      "Like a flower turning toward the sun",
      "Ready to receive and give love",
      "",
      "Now imagine walking into a beautiful garden",
      "This is the garden of your heart",
      "Notice what you see here",
      "Perhaps there are flowers already blooming",
      "Perhaps some areas need tending",
      "All of it is welcome, all of it is yours",
      "",
      "In this garden, we will plant seeds of loving-kindness",
      "First, we plant seeds for ourselves",
      "Because we cannot give what we don't have",
      "We must fill our own garden first",
      "",
      "Take a seed of compassion in your hand",
      "This seed contains infinite potential",
      "Place it gently in the soil of your heart",
      "And speak these words silently",
      "May I be happy and peaceful",
      "May I be safe and protected",
      "May I be healthy and strong",
      "May I live with ease and joy",
      "",
      "Feel these wishes taking root in your heart",
      "Like seeds sprouting in fertile soil",
      "Water them with your breath",
      "Warm them with your attention",
      "Watch as they begin to grow",
      "",
      "Now think of someone you love dearly",
      "Someone whose happiness brings you joy",
      "See their face clearly in your mind",
      "Feel the love you have for them",
      "Take another seed of loving-kindness",
      "",
      "Plant this seed for your loved one",
      "As you place it in your heart's garden, say",
      "May you be happy and peaceful",
      "May you be safe and protected",
      "May you be healthy and strong",
      "May you live with ease and joy",
      "",
      "See this love growing like a beautiful flower",
      "Its fragrance filling your entire garden",
      "Your love for them nourishes your own heart",
      "There is no separation in the garden of love",
      "",
      "Now bring to mind someone neutral",
      "Perhaps someone you see but don't really know",
      "A neighbor, a cashier, a passing stranger",
      "They too deserve a place in your garden",
      "Take another seed of kindness",
      "",
      "Plant it with the same care, saying",
      "May you be happy and peaceful",
      "May you be safe and protected", 
      "May you be healthy and strong",
      "May you live with ease and joy",
      "",
      "Notice how your garden expands",
      "Love doesn't diminish when shared",
      "It multiplies and grows stronger",
      "Your heart has infinite space",
      "",
      "Now, with courage, think of someone difficult",
      "Someone who has caused you pain or frustration",
      "This is the most powerful practice",
      "For even weeds can become flowers",
      "When touched by compassion",
      "",
      "Take a seed of understanding",
      "Know that this person, like you, suffers",
      "They too want to be happy",
      "They too fear pain and loss",
      "Plant this seed gently, saying",
      "May you be free from suffering",
      "May you find peace",
      "May you be happy",
      "May you be healed",
      "",
      "This doesn't mean accepting harmful behavior",
      "It means freeing your heart from resentment",
      "Letting your garden bloom instead of wither",
      "Choosing love over bitterness",
      "",
      "Now expand your garden to all beings",
      "Let your loving-kindness grow boundless",
      "Include all humans, all animals",
      "All forms of life on this planet",
      "Plant seeds of universal love",
      "",
      "May all beings be happy and peaceful",
      "May all beings be safe and protected",
      "May all beings be healthy and strong",
      "May all beings live with ease and joy",
      "",
      "See your garden now in full bloom",
      "Flowers of every color and variety",
      "The fragrance of compassion everywhere",
      "This is the true nature of your heart",
      "This is who you really are",
      "",
      "Rest in this garden of boundless love",
      "Know that you can return here always",
      "With each act of kindness, you water these seeds",
      "With each moment of compassion, they grow stronger",
      "",
      "Take a deep breath of this sweet fragrance",
      "Let it fill every cell of your being",
      "You are both the gardener and the garden",
      "You are both the love and the beloved",
      "",
      "When you're ready, gently open your eyes",
      "But keep your garden blooming within",
      "As you meet others today",
      "Remember the seeds you've planted",
      "Let your love flower in the world"
    ]
  },
  {
    id: "creative-flow",
    title: "River of Creativity",
    description: "Unlock the flowing river of creativity within you. Remove the dams of doubt and let inspiration flow freely through your being.",
    author: "Words by Genie",
    voice: "Voice by Genie",
    category: "creativity",
    colorTheme: {
      center: 'rgba(255, 220, 180, 0.95)',
      mid1: 'rgba(255, 200, 160, 0.9)',
      mid2: 'rgba(240, 180, 140, 0.8)',
      edge: 'rgba(220, 160, 120, 0.6)',
    },
    content: [
      "Welcome to this journey into creative flow",
      "Settle into a comfortable position",
      "Let your body relax and your mind open",
      "You are about to connect with the river of creativity",
      "That flows eternally within you",
      "",
      "Begin with three inspiring breaths",
      "Each inhale drawing in possibility",
      "Each exhale releasing limitation",
      "Feel yourself becoming more spacious",
      "More open to what wants to emerge",
      "",
      "Imagine standing beside a beautiful river",
      "This river represents your creative flow",
      "Notice its current, how it moves",
      "Sometimes fast and playful",
      "Sometimes slow and deep",
      "Always flowing, always alive",
      "",
      "This river has always been within you",
      "From your first breath, it began to flow",
      "Every moment of wonder you've experienced",
      "Every spark of imagination",
      "Has been this river expressing itself",
      "",
      "Step closer to the water's edge",
      "See how the river catches the light",
      "Sparkling with infinite possibilities",
      "Each ripple a potential idea",
      "Each wave a creative impulse",
      "",
      "Now notice any dams in your river",
      "These are the blocks to your creativity",
      "Perhaps the dam of perfectionism",
      "Built from fears of not being good enough",
      "See it there, solid but not permanent",
      "",
      "Or maybe the dam of comparison",
      "Constructed from looking at others",
      "Instead of honoring your unique flow",
      "Recognize these dams with compassion",
      "They were built for protection, but now they limit you",
      "",
      "Take a deep breath and imagine",
      "These dams beginning to dissolve",
      "Not through force, but through understanding",
      "Like ice melting in spring sunshine",
      "Allowing your river to flow more freely",
      "",
      "Feel the relief as the water moves",
      "Your creativity has been waiting",
      "Patient but eager to flow",
      "It doesn't judge or criticize",
      "It simply wants to express",
      "",
      "Step into your river of creativity",
      "Feel the water flowing around you",
      "Cool and refreshing, alive with energy",
      "This is your natural element",
      "This is where you belong",
      "",
      "Notice how the river knows its way",
      "It doesn't force, it flows",
      "Around obstacles, over rocks",
      "Always finding the path forward",
      "Trust your creativity to do the same",
      "",
      "In this river, there are no mistakes",
      "Only experiments and explorations",
      "Each creative act is perfect",
      "Because it's authentic to this moment",
      "Let go of outcomes and swim in process",
      "",
      "Feel ideas bubbling up from the depths",
      "Like springs feeding the river",
      "You don't create these ideas",
      "You receive them, channel them",
      "You are the riverbed through which creativity flows",
      "",
      "Your unique shape gives form to the flow",
      "No one else can express exactly as you do",
      "Your perspective is a gift to the world",
      "Your creativity is needed",
      "Let it flow without apology",
      "",
      "Notice how playing in this river feels",
      "The joy of splashing without purpose",
      "The delight of discovering new currents",
      "Creativity is your birthright",
      "As natural as breathing",
      "",
      "When you create from this flow state",
      "Time disappears, self-consciousness fades",
      "You become one with the creative force",
      "That moves through all of life",
      "This is your true nature expressing itself",
      "",
      "Float now in your creative river",
      "Let it carry you without effort",
      "Trust where it wants to take you",
      "Every destination is perfect",
      "Every journey is complete",
      "",
      "Know that this river never runs dry",
      "It's connected to the infinite ocean",
      "Of universal creativity",
      "You can return here whenever you wish",
      "The flow is always available",
      "",
      "Take a deep breath of creative energy",
      "Feel it filling every cell",
      "You are creativity itself",
      "Expressing through human form",
      "Magnificent and unlimited",
      "",
      "When you're ready, step out of the river",
      "But notice how it continues to flow within you",
      "As you open your eyes",
      "See the world with creative vision",
      "Everything is possible, everything is material",
      "",
      "Go forth and create",
      "Not because you have to",
      "But because it's your joy",
      "Let your river flow into the world",
      "Blessing all it touches with beauty and truth"
    ]
  },
  {
    id: "healing-light",
    title: "Healing Light Meditation",
    description: "Journey through a powerful healing visualization, allowing golden light to restore and rejuvenate every part of your being—body, mind, and spirit.",
    author: "Words by Genie",
    voice: "Voice by Genie",
    category: "healing",
    colorTheme: {
      center: 'rgba(255, 240, 200, 0.95)',
      mid1: 'rgba(255, 230, 180, 0.9)',
      mid2: 'rgba(255, 220, 160, 0.8)',
      edge: 'rgba(240, 200, 140, 0.6)',
    },
    content: [
      "Welcome to this healing light meditation",
      "A journey of restoration and renewal",
      "Find a position where your body can fully relax",
      "You may lie down or sit comfortably",
      "Give yourself permission to receive healing",
      "",
      "Close your eyes and take three cleansing breaths",
      "With each exhale, release any tension",
      "With each inhale, invite healing energy",
      "Your body knows how to heal",
      "Trust in its infinite wisdom",
      "",
      "Above you now, imagine a sphere of golden light",
      "Pure, warm, and infinitely loving",
      "This is healing light from the source of all life",
      "It contains perfect health and wholeness",
      "It's here specifically for you",
      "",
      "This golden sphere begins to descend slowly",
      "As it approaches, you feel its warmth",
      "Like sunshine on a perfect day",
      "It pauses just above your head",
      "Pulsing with healing energy",
      "",
      "Now the light begins to pour down",
      "Entering through the crown of your head",
      "Feel it flowing like warm honey",
      "Filling your skull with golden radiance",
      "Every cell of your brain bathes in this light",
      "",
      "Any thoughts of illness or imbalance",
      "Simply dissolve in this healing presence",
      "Your mind becomes clear and peaceful",
      "Restored to its natural state",
      "Of clarity and calm",
      "",
      "The light continues flowing downward",
      "Into your face, relaxing every muscle",
      "Your eyes soften and heal",
      "Your ears open to harmony",
      "Your mouth and jaw release all tension",
      "",
      "Feel the light flowing into your throat",
      "Healing your voice, your expression",
      "Any words unspoken are blessed and released",
      "Your throat glows with golden light",
      "Free and open",
      "",
      "Now into your shoulders the light flows",
      "These shoulders that have carried so much",
      "Feel them melting, softening, healing",
      "The golden light dissolves all burdens",
      "Leaving only strength and ease",
      "",
      "The light pours down your arms",
      "Through your elbows, forearms, and wrists",
      "Into your hands and fingers",
      "These hands that give and receive",
      "Now glow with healing power",
      "",
      "Into your chest the golden light flows",
      "Surrounding your heart with love",
      "Any old wounds or heartaches",
      "Are gently touched and healed",
      "Your heart expands with golden radiance",
      "",
      "Your lungs fill with healing light",
      "Every breath now carries golden energy",
      "In and out, healing and cleansing",
      "Your entire respiratory system",
      "Glows with perfect health",
      "",
      "The light flows into your solar plexus",
      "Your center of personal power",
      "Strengthening your will and confidence",
      "Healing any fears or doubts",
      "You glow with inner strength",
      "",
      "Down into your belly the light pours",
      "Healing your digestive system completely",
      "Every organ bathed in golden radiance",
      "Functioning in perfect harmony",
      "Nourishing and sustaining you",
      "",
      "The light flows into your lower back",
      "Releasing any pain or tension",
      "Your spine becomes a channel of light",
      "Strong, flexible, and aligned",
      "Supporting you perfectly",
      "",
      "Into your hips and pelvis the healing flows",
      "Releasing old emotions stored here",
      "Your creative and sexual energy",
      "Is blessed and restored",
      "To its natural, healthy flow",
      "",
      "Down through your thighs the light travels",
      "These powerful muscles that carry you forward",
      "Are renewed with golden energy",
      "Strong and flexible",
      "Ready for life's journey",
      "",
      "Through your knees, those faithful joints",
      "The light brings flexibility and ease",
      "Into your calves and shins",
      "Down to your ankles and feet",
      "Every part glowing with health",
      "",
      "Your entire body is now filled with golden light",
      "From head to toe, you radiate healing energy",
      "But the meditation continues deeper",
      "Into the emotional and spiritual bodies",
      "For true healing encompasses all levels",
      "",
      "See this golden light expanding beyond your skin",
      "Filling your emotional body",
      "Any sadness, anger, or fear",
      "Is transformed by this loving light",
      "Into peace, joy, and courage",
      "",
      "The light expands further still",
      "Filling your spiritual body",
      "Connecting you to your highest self",
      "To the source of all healing",
      "You remember your divine perfection",
      "",
      "Rest now in this golden radiance",
      "Every cell vibrating with health",
      "Every system functioning perfectly",
      "You are whole, you are healed",
      "You are restored to your true nature",
      "",
      "This healing light remains with you",
      "It has become part of your being",
      "You can activate it anytime",
      "Simply by remembering this moment",
      "By breathing in golden light",
      "",
      "Take three deep breaths to seal this healing",
      "Know that the process continues",
      "Even after this meditation ends",
      "Your body will integrate this light",
      "In perfect timing and perfect ways",
      "",
      "When you're ready, wiggle your fingers and toes",
      "Gently stretch your body",
      "Open your eyes when it feels right",
      "See the world through healed eyes",
      "You are renewed, restored, and radiant"
    ]
  },
  {
    id: "inner-child",
    title: "Embracing Your Inner Child",
    description: "Reconnect with the innocent, playful, and wise child within you. Heal old wounds and rediscover the joy and wonder that is your birthright.",
    author: "Words by Genie",
    voice: "Voice by Genie",
    category: "healing",
    colorTheme: {
      center: 'rgba(255, 230, 210, 0.95)',
      mid1: 'rgba(255, 210, 190, 0.9)',
      mid2: 'rgba(240, 190, 170, 0.8)',
      edge: 'rgba(220, 170, 150, 0.6)',
    },
    content: [
      "Welcome to this sacred meeting with your inner child",
      "A journey of healing, play, and rediscovery",
      "Settle into a comfortable position",
      "Allow yourself to feel safe and supported",
      "This is a gentle journey home to yourself",
      "",
      "Take three soft breaths",
      "With each breath, let your heart open a little more",
      "We're creating a safe space",
      "For a very special reunion",
      "",
      "Imagine yourself in a beautiful, safe place",
      "Perhaps a garden, a cozy room, or a magical forest",
      "This is your inner sanctuary",
      "Where all parts of you are welcome",
      "Where healing naturally occurs",
      "",
      "In this space, you notice a path",
      "It leads to a special meeting place",
      "Follow this path with curiosity",
      "Each step takes you deeper within",
      "To where your inner child waits",
      "",
      "As you walk, remember",
      "Your inner child has always been with you",
      "Sometimes hidden, sometimes hurt",
      "But always present, always precious",
      "Carrying gifts of wonder and joy",
      "",
      "You come to a clearing or doorway",
      "And there you see a young version of yourself",
      "Notice what age they appear to be",
      "How they look, what they're wearing",
      "Let them appear exactly as they are",
      "",
      "See the expression on their face",
      "Are they shy, excited, cautious?",
      "Whatever they're feeling is perfect",
      "Approach them slowly, gently",
      "With love in your heart",
      "",
      "Kneel down to their eye level",
      "Or sit beside them comfortably",
      "Let them know you're here now",
      "The adult they'll become",
      "And you've come to visit",
      "",
      "Tell them, 'I see you'",
      "'I'm here for you'",
      "'You are safe with me'",
      "Watch how they respond",
      "Give them time to trust",
      "",
      "Ask your inner child what they need",
      "Listen with your whole heart",
      "Maybe they need to be held",
      "Maybe they need to be heard",
      "Maybe they just need to play",
      "",
      "If they're ready, hold them close",
      "Let them feel your strength and love",
      "Tell them all the things",
      "You wished someone had said to you",
      "When you were young",
      "",
      "'You are perfect just as you are'",
      "'Your feelings matter'",
      "'It's not your fault'",
      "'You are so loved'",
      "'I'm proud of you'",
      "",
      "Feel the healing that happens",
      "When these words are received",
      "Your inner child may cry",
      "May laugh, may want to play",
      "All responses are welcome",
      "",
      "Ask what brings them joy",
      "What did they love to do?",
      "What dreams did they have?",
      "What made their eyes light up?",
      "Listen to their excitement",
      "",
      "Remember, this child holds your creativity",
      "Your capacity for wonder",
      "Your ability to see magic",
      "In the ordinary world",
      "These gifts never left you",
      "",
      "Play with your inner child now",
      "Let them show you their world",
      "Maybe you dance together",
      "Maybe you draw or imagine",
      "Maybe you simply laugh",
      "",
      "Feel how natural this connection is",
      "This isn't just memory",
      "This is a living part of you",
      "Deserving of attention and care",
      "Offering wisdom and joy",
      "",
      "Tell your inner child",
      "That you'll visit often now",
      "That they don't have to hide anymore",
      "That their feelings are welcome",
      "That together, you are whole",
      "",
      "Ask if they have a message for you",
      "Something to remember",
      "As you go about your adult life",
      "Listen carefully to their wisdom",
      "Children see truth clearly",
      "",
      "Now invite your inner child",
      "To merge with your heart",
      "Let them know they can live there",
      "Safe, loved, and free",
      "Part of everything you do",
      "",
      "Feel them stepping into your heart space",
      "Bringing their light with them",
      "Your heart expands to hold them",
      "You are no longer separated",
      "You are integrated and whole",
      "",
      "Notice how you feel now",
      "With your inner child restored",
      "Perhaps lighter, more playful",
      "Perhaps more compassionate",
      "Certainly more complete",
      "",
      "Take a deep breath together",
      "Adult and child as one",
      "Feel the joy of this reunion",
      "The healing of this integration",
      "The promise of new adventures",
      "",
      "Know that you can return here",
      "Whenever you need connection",
      "Your inner child is always with you",
      "In your laughter, your tears",
      "Your curiosity and wonder",
      "",
      "Slowly begin to return",
      "Bringing this childlike energy with you",
      "When you open your eyes",
      "See the world as your inner child does",
      "Full of possibility and magic",
      "",
      "Welcome home to wholeness",
      "Welcome home to joy",
      "Welcome home to yourself",
      "Complete, integrated, and free",
      "Child and adult, united in love"
    ]
  },
  {
    id: "abundance-mindset",
    title: "Abundance Consciousness",
    description: "Shift from scarcity to abundance, opening your mind and heart to the infinite flow of prosperity, love, and opportunities that surround you.",
    author: "Words by Genie",
    voice: "Voice by Genie",
    category: "gratitude",
    colorTheme: {
      center: 'rgba(255, 215, 180, 0.95)',
      mid1: 'rgba(240, 200, 160, 0.9)',
      mid2: 'rgba(225, 185, 140, 0.8)',
      edge: 'rgba(210, 170, 120, 0.6)',
    },
    content: [
      "Welcome to this meditation on abundance consciousness",
      "A journey from scarcity to overflow",
      "Find your comfortable position",
      "Let your body settle and relax",
      "Open yourself to receive",
      "",
      "Begin with three expansive breaths",
      "Each inhale drawing in possibility",
      "Each exhale releasing limitation",
      "Feel your energy field expanding",
      "Making room for abundance",
      "",
      "Place your hands on your heart",
      "Feel the richness that already exists within you",
      "Your heartbeat is abundance in action",
      "Giving and receiving in perfect rhythm",
      "Never running out, always flowing",
      "",
      "Consider the abundance of your breath",
      "Have you ever worried about running out of air?",
      "The universe provides each breath freely",
      "Infinitely available, perfectly timed",
      "This is the nature of true abundance",
      "",
      "Now expand your awareness to nature",
      "Think of how many leaves are on one tree",
      "How many trees in a forest",
      "How many seeds in one flower",
      "Nature doesn't hold back, it overflows",
      "",
      "You are part of this abundant universe",
      "Made of the same creative energy",
      "That forms galaxies and grows gardens",
      "Abundance is your natural state",
      "Scarcity is just a forgetting",
      "",
      "Notice any beliefs about lack",
      "Where do you feel scarcity in your body?",
      "Perhaps tightness in your chest",
      "Or constriction in your throat",
      "Breathe gently into these areas",
      "",
      "These beliefs were learned, not true",
      "Perhaps passed down through generations",
      "Survival fears that once served a purpose",
      "But now only limit your flow",
      "You can choose new beliefs",
      "",
      "Imagine a golden river of abundance",
      "Flowing from the source of all creation",
      "This river wants to flow through you",
      "You are meant to be a channel",
      "Not a dam holding back the flow",
      "",
      "What would it feel like to trust",
      "That there's always enough?",
      "Enough money, enough love",
      "Enough time, enough opportunities",
      "Feel this trust in your body",
      "",
      "Abundance is not about greed",
      "It's about recognizing truth",
      "When you know there's enough",
      "You naturally share more freely",
      "Your overflow blesses others",
      "",
      "Think of all the abundance you already have",
      "The wealth of experiences you've gathered",
      "The treasury of memories",
      "The riches of relationships",
      "The fortune of your abilities",
      "",
      "Count the abundance of your senses",
      "How many colors can your eyes see?",
      "How many sounds can your ears hear?",
      "How many textures can you feel?",
      "You are wealthy beyond measure",
      "",
      "Now imagine abundance in all forms",
      "Flowing into your life with ease",
      "See opportunities appearing naturally",
      "Resources coming when needed",
      "Support arriving in perfect timing",
      "",
      "Feel how different this is",
      "From chasing or grasping",
      "Abundance flows to an open hand",
      "Not a clenched fist",
      "Relax and receive",
      "",
      "Repeat these affirmations silently",
      "'I am open to abundance'",
      "'I deserve prosperity in all forms'",
      "'I trust life to provide'",
      "'I am a channel for abundance'",
      "'My abundance serves the highest good'",
      "",
      "See yourself as a fountain",
      "Abundance flowing up from within",
      "And overflowing to bless others",
      "The more you give, the more you receive",
      "This is the law of circulation",
      "",
      "What would you do differently",
      "If you truly believed in abundance?",
      "How would you share your gifts?",
      "What dreams would you pursue?",
      "Feel the freedom this brings",
      "",
      "Abundance is not just material",
      "It's abundant peace, abundant joy",
      "Abundant creativity, abundant love",
      "Abundant health, abundant time",
      "All forms of wealth are available",
      "",
      "Breathe in abundance consciousness",
      "Let it fill every cell",
      "You are rewiring old patterns",
      "Creating new neural pathways",
      "Of prosperity and flow",
      "",
      "Know that this shift is permanent",
      "As you practice this awareness",
      "Watch how life responds",
      "With synchronicities and surprises",
      "Confirming your abundant nature",
      "",
      "Take three deep breaths of gratitude",
      "For all the abundance already present",
      "And all that's on its way",
      "You are a magnet for good",
      "A beacon of prosperity",
      "",
      "When you're ready, open your eyes",
      "See the world through abundant vision",
      "Notice wealth everywhere",
      "In smiles, in nature, in possibilities",
      "You live in an abundant universe",
      "",
      "Go forth knowing you are provided for",
      "Share generously, receive gracefully",
      "Trust the infinite flow",
      "You are abundance itself",
      "Expressing in human form"
    ]
  },
  {
    id: "quantum-consciousness",
    title: "Quantum Field Meditation",
    description: "Explore the quantum field of infinite possibilities. Step beyond linear time and space into the realm where thoughts become reality and consciousness creates matter.",
    author: "Words by Genie",
    voice: "Voice by Genie",
    category: "focus",
    colorTheme: {
      center: 'rgba(220, 200, 255, 0.95)',
      mid1: 'rgba(200, 180, 245, 0.9)',
      mid2: 'rgba(180, 160, 235, 0.8)',
      edge: 'rgba(160, 140, 220, 0.6)',
    },
    content: [
      "Welcome to the quantum field meditation",
      "A journey beyond the physical",
      "Into the realm of pure potential",
      "Where consciousness meets creation",
      "Where you discover your power to shape reality",
      "",
      "Settle into stillness",
      "Let your body find perfect comfort",
      "Close your eyes and turn inward",
      "We're going to explore",
      "The deepest levels of existence",
      "",
      "Begin with three quantum breaths",
      "Breathing in pure potential",
      "Breathing out old limitations",
      "With each breath, become lighter",
      "Less solid, more wavelike",
      "",
      "Imagine your body beginning to dissolve",
      "Not in a frightening way",
      "But like sugar dissolving in warm water",
      "Your particles spreading out",
      "Becoming spacious and free",
      "",
      "You are entering the quantum field",
      "Where matter is mostly empty space",
      "Where particles exist as probabilities",
      "Until consciousness observes them",
      "Into specific locations",
      "",
      "Feel yourself as energy now",
      "Vibrating, pulsing, alive",
      "You are both particle and wave",
      "Both matter and consciousness",
      "Both observer and observed",
      "",
      "In this quantum realm",
      "Past, present, and future exist simultaneously",
      "All possibilities are available",
      "All timelines are accessible",
      "You are free from linear time",
      "",
      "Notice the field around you",
      "Shimmering with potential",
      "Like a vast ocean of energy",
      "Responsive to your thoughts",
      "Shaped by your intentions",
      "",
      "In quantum physics, observation creates reality",
      "What you focus on manifests",
      "Your consciousness is the creative force",
      "That collapses waves of possibility",
      "Into particles of experience",
      "",
      "Feel your power as a conscious observer",
      "Every thought sends ripples through the field",
      "Every emotion shifts the energy",
      "Every belief shapes what's possible",
      "You are constantly creating",
      "",
      "Now bring to mind something you wish to create",
      "Hold it gently in your awareness",
      "Don't force or strain",
      "Simply observe it with loving attention",
      "Feel it as already existing in the field",
      "",
      "In the quantum field, it already exists",
      "All possibilities are present",
      "Your job is to tune your frequency",
      "To match what you wish to experience",
      "Like tuning into a radio station",
      "",
      "Feel the frequency of your desire",
      "How does it vibrate?",
      "What energy does it carry?",
      "Begin to resonate with this frequency",
      "Become one with it",
      "",
      "This is not wishful thinking",
      "This is quantum mechanics",
      "Consciousness influences matter",
      "Intention shapes probability",
      "You are working with universal laws",
      "",
      "Let go of how it will manifest",
      "The quantum field has infinite intelligence",
      "It knows pathways you cannot see",
      "Trust the field to orchestrate",
      "The perfect unfolding",
      "",
      "Feel yourself entangled with all existence",
      "In quantum entanglement",
      "Separated particles remain connected",
      "You are connected to everything",
      "Your wellbeing affects the whole",
      "",
      "From this place of connection",
      "Send love through the quantum field",
      "To all beings, all situations",
      "Watch how the field responds",
      "With waves of love returning",
      "",
      "You are both local and non-local",
      "Both here and everywhere",
      "Both individual and universal",
      "This is your quantum nature",
      "Vast, mysterious, powerful",
      "",
      "Rest in this expanded state",
      "Beyond the illusion of separation",
      "Beyond the limits of physical laws",
      "You are consciousness itself",
      "Exploring its own infinite nature",
      "",
      "In this field, healing happens instantly",
      "Transformation occurs outside time",
      "Miracles are natural",
      "Because you're working at the causal level",
      "Where reality is created",
      "",
      "Take a moment to appreciate",
      "The magnificent being you are",
      "Made of stardust and consciousness",
      "Capable of influencing reality",
      "Through the power of aware presence",
      "",
      "Now slowly begin to return",
      "Bringing quantum awareness with you",
      "Feel your particles condensing",
      "Back into physical form",
      "But maintaining field awareness",
      "",
      "You can access this field anytime",
      "Through meditation, through presence",
      "Through conscious breathing",
      "You are always connected",
      "To infinite possibility",
      "",
      "Take three integrating breaths",
      "Feeling yourself fully here",
      "Yet still connected to the field",
      "You are the bridge",
      "Between quantum and physical",
      "",
      "When you open your eyes",
      "See the world differently",
      "Everything is energy",
      "Everything is connected",
      "Everything is possible",
      "",
      "Live from this quantum awareness",
      "Create from this field of potential",
      "You are more powerful than you know",
      "Reality is more fluid than it appears",
      "Welcome to quantum consciousness"
    ]
  },
  {
    id: "forest-bathing",
    title: "Forest Bathing Journey",
    description: "Immerse yourself in the healing presence of an ancient forest. Let the wisdom of trees and the peace of nature restore your natural rhythm and connection to Earth.",
    author: "Words by Genie",
    voice: "Voice by Genie",
    category: "mindfulness",
    colorTheme: {
      center: 'rgba(180, 220, 180, 0.95)',
      mid1: 'rgba(160, 200, 160, 0.9)',
      mid2: 'rgba(140, 180, 140, 0.8)',
      edge: 'rgba(120, 160, 120, 0.6)',
    },
    content: [
      "Welcome to this forest bathing journey",
      "A practice of deep communion with nature",
      "Make yourself comfortable",
      "You're about to enter an ancient forest",
      "Where healing happens naturally",
      "",
      "Close your eyes and take three deep breaths",
      "With each breath, feel yourself leaving",
      "The world of concrete and screens",
      "And entering the living world",
      "Of growth and green wisdom",
      "",
      "You find yourself at the edge of a forest",
      "The trees stand tall before you",
      "Inviting you to enter their sanctuary",
      "Step forward across the threshold",
      "From civilization into wildness",
      "",
      "Immediately, the air changes",
      "It's cooler, richer, more alive",
      "Filled with the breath of trees",
      "The oxygen they gift freely",
      "Breathe deeply of this forest air",
      "",
      "Notice the quality of light here",
      "Filtered through countless leaves",
      "Creating a green cathedral",
      "Dappled sunshine dances",
      "On the forest floor",
      "",
      "Feel the earth beneath your feet",
      "Soft with decades of fallen leaves",
      "Each step connects you more deeply",
      "To the mycelial network below",
      "The wood wide web of connection",
      "",
      "The trees around you are ancient beings",
      "Some have stood for centuries",
      "Witnessing countless seasons",
      "They emanate profound peace",
      "And timeless wisdom",
      "",
      "Place your hand on a tree trunk",
      "Feel its texture, its solidity",
      "This tree is more than wood",
      "It's a living community",
      "Of bark, sap, and countless creatures",
      "",
      "Lean against this tree",
      "Feel its support, its strength",
      "It has weathered every storm",
      "By being flexible yet rooted",
      "Let it teach you resilience",
      "",
      "Listen to the forest symphony",
      "Leaves rustling in the breeze",
      "Birds calling tree to tree",
      "Insects humming their songs",
      "The forest is never silent",
      "",
      "Breathe with the trees now",
      "As you exhale carbon dioxide",
      "They breathe it in gratefully",
      "As they exhale oxygen",
      "You receive their gift of life",
      "",
      "This is true reciprocity",
      "You are not separate from this forest",
      "You are part of its breathing",
      "Part of its living system",
      "You belong here",
      "",
      "Walk deeper into the forest",
      "Let your feet find their own path",
      "There's no destination",
      "Only presence, only connection",
      "Only this moment in the green world",
      "",
      "Find a place to sit",
      "Perhaps against a tree",
      "Or on a moss-covered log",
      "Settle into forest time",
      "Where hurry doesn't exist",
      "",
      "Close your eyes and expand your awareness",
      "Feel the forest feeling you",
      "You are being observed",
      "By countless gentle eyes",
      "Welcomed as family",
      "",
      "The Japanese call this shinrin-yoku",
      "Forest bathing, taking in the forest atmosphere",
      "It's medicine for body and soul",
      "Lowering stress, boosting immunity",
      "Returning you to natural rhythm",
      "",
      "Feel the phytoncides",
      "The essential oils trees release",
      "Entering your lungs, your bloodstream",
      "These compounds boost your immune system",
      "The forest is healing you",
      "",
      "Notice any birds that come near",
      "They are the forest's messengers",
      "What do their songs tell you?",
      "What wisdom do they carry",
      "On their small wings?",
      "",
      "Feel the peace that lives here",
      "Not the absence of sound",
      "But the presence of harmony",
      "Everything in right relationship",
      "Everything in its place",
      "",
      "You may have come here feeling scattered",
      "Like leaves blown by winds of worry",
      "But the forest gathers you",
      "Calls all your parts home",
      "Roots you back into wholeness",
      "",
      "This is your original home",
      "Humans evolved in forests",
      "Your body remembers this",
      "Your cells recognize this peace",
      "You are coming home",
      "",
      "Let the forest wisdom enter you",
      "The patience of trees",
      "The persistence of roots",
      "The flexibility of branches",
      "The generosity of shade",
      "",
      "Stay here as long as you need",
      "There's no rush to leave",
      "The forest operates on tree time",
      "Slow, seasonal, sustainable",
      "Rest in this ancient rhythm",
      "",
      "When you're ready to return",
      "Thank the forest for its gifts",
      "Know you can visit anytime",
      "In meditation, in memory",
      "The forest lives within you now",
      "",
      "Slowly open your eyes",
      "But keep the forest feeling",
      "As you return to daily life",
      "Remember you are never separate",
      "From the natural world",
      "",
      "You carry the forest's peace",
      "Its wisdom, its healing",
      "Let it guide your choices",
      "Toward sustainability and harmony",
      "You are part of the living Earth"
    ]
  },
  {
    id: "cosmic-connection",
    title: "Cosmic Connection",
    description: "Journey beyond Earth to experience your place in the cosmos. Feel your connection to stars, planets, and the infinite universe that birthed you.",
    author: "Words by Genie",
    voice: "Voice by Genie",
    category: "mindfulness",
    colorTheme: {
      center: 'rgba(200, 180, 255, 0.95)',
      mid1: 'rgba(180, 160, 245, 0.9)',
      mid2: 'rgba(160, 140, 235, 0.8)',
      edge: 'rgba(140, 120, 220, 0.6)',
    },
    content: [
      "Welcome to this cosmic journey",
      "A meditation on your place in the universe",
      "Settle into profound comfort",
      "You're about to travel beyond Earth",
      "To remember your cosmic origins",
      "",
      "Close your eyes and breathe deeply",
      "With each breath, feel yourself becoming lighter",
      "Less bound by gravity",
      "More expansive and free",
      "Ready for cosmic flight",
      "",
      "Imagine yourself gently lifting",
      "Up from where you sit",
      "Through the ceiling, through the clouds",
      "Higher and higher you rise",
      "The Earth shrinking below",
      "",
      "You pass through the atmosphere",
      "That thin blue line protecting all life",
      "And emerge into the vastness of space",
      "Silent, infinite, magnificent",
      "This is your larger home",
      "",
      "Float here in the cosmic void",
      "Look back at Earth",
      "That beautiful blue marble",
      "No borders visible from here",
      "Just one living system",
      "",
      "See how precious it is",
      "This oasis of life",
      "In the vast cosmic desert",
      "Your home, your mother",
      "Suspended in the void",
      "",
      "Now turn to face the cosmos",
      "Billions of stars surround you",
      "Each one a sun",
      "Perhaps with worlds of its own",
      "The universe is teeming",
      "",
      "Feel your body made of stardust",
      "Every atom forged in stellar cores",
      "You are not on Earth looking up at stars",
      "You are the universe looking at itself",
      "Through human eyes",
      "",
      "Expand your awareness further",
      "See the spiral arm of our galaxy",
      "The Milky Way, our cosmic neighborhood",
      "400 billion stars swirling",
      "In a cosmic dance",
      "",
      "And beyond, countless galaxies",
      "Each containing billions of stars",
      "The scale is incomprehensible",
      "Yet here you are, conscious",
      "Able to contemplate it all",
      "",
      "Feel the profound mystery",
      "How did atoms become aware?",
      "How did matter develop minds?",
      "You are the universe's way",
      "Of knowing itself",
      "",
      "Connect with the cosmic rhythm",
      "Everything spinning, orbiting, dancing",
      "Planets around stars",
      "Stars around galactic centers",
      "Galaxies in cosmic webs",
      "",
      "You are part of this dance",
      "Your electrons orbit nuclei",
      "Your Earth orbits the Sun",
      "Everything is movement",
      "Everything is connected",
      "",
      "Feel the cosmic forces",
      "Gravity's embrace holding all together",
      "Dark energy expanding space itself",
      "Electromagnetic radiation",
      "Carrying information across infinity",
      "",
      "You are woven from these forces",
      "Not separate from the cosmos",
      "But an expression of it",
      "As natural as nebulae",
      "As essential as stars",
      "",
      "Contemplate the cosmic timeline",
      "13.8 billion years of evolution",
      "From the first hydrogen atoms",
      "To the complexity of your consciousness",
      "What a journey it's been",
      "",
      "You are the current edge",
      "Of cosmic evolution",
      "Through you, the universe reflects",
      "On its own existence",
      "What a privilege this is",
      "",
      "Feel gratitude for this cosmic moment",
      "For the improbability of your existence",
      "For consciousness itself",
      "For the ability to love",
      "To create, to wonder",
      "",
      "From this cosmic perspective",
      "How small earthly worries seem",
      "Yet how precious each moment becomes",
      "When you know how rare",
      "Conscious life really is",
      "",
      "You are both insignificant",
      "And supremely significant",
      "A tiny speck in infinity",
      "Yet the very eyes through which",
      "Infinity beholds itself",
      "",
      "Rest in this cosmic paradox",
      "Embracing both your smallness",
      "And your cosmic nature",
      "You are a child of the universe",
      "No less than the trees and stars",
      "",
      "Now slowly begin your return",
      "Carrying cosmic consciousness with you",
      "Through the stars, through space",
      "Back to our beautiful Earth",
      "Your planetary home",
      "",
      "Re-enter the atmosphere",
      "Feel gravity's gentle embrace",
      "Welcoming you home",
      "But you are changed",
      "You remember your cosmic nature",
      "",
      "Settle back into your body",
      "This stardust made conscious",
      "Feel your feet on the ground",
      "Your head among the stars",
      "Bridge between Earth and cosmos",
      "",
      "Take three grounding breaths",
      "Integrating this vast perspective",
      "You are simultaneously",
      "Cosmic and intimate",
      "Universal and unique",
      "",
      "When you open your eyes",
      "See with cosmic vision",
      "Everything is sacred",
      "Everything is connected",
      "Everything is stardust awakened",
      "",
      "Live with this awareness",
      "You are the universe in human form",
      "Every person you meet",
      "Is another face of cosmos",
      "We are all one thing, exploring itself",
      "",
      "Welcome back, cosmic traveler",
      "Welcome back, conscious stardust",
      "Welcome back to Earth",
      "Your feet on the ground",
      "Your soul among stars"
    ]
  }
];

// Export complete meditation topics with calculated durations
export const meditationTopics: MeditationTopic[] = meditationContent.map(topic => ({
  ...topic,
  duration: calculateDuration(topic.content)
}));